name: CI/CD Pipeline 

on: [push]

jobs:
  train_and_test:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      # Checkout code 
      - name: Checkout code
        uses: actions/checkout@v3

      # Cài đặt các thư viện 
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install -g @dvcorg/cml 

      # Train model và log kết quả
      - name: Train Model and Log Results
        run: |
          python src/train.py
          echo "# Training Report" > report.md
          cat metrics.txt >> report.md
          echo "![](./residuals.png)" >> report.md

      # Test model 
      - name: Run tests
        run: |
          python src/test.py
          echo "## Single test Results" >> report.md
          cat single_test.txt >> report.md


      - name: Report
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cml comment create report.md

  build:
    needs: train_and_test 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-demo:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-demo:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl v1.30
        run: |
          curl -LO "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Replace Docker Hub username in deployment.yml
        run: |
          sed -i 's|<DOCKER_HUB_USERNAME>|${{ secrets.DOCKER_HUB_USERNAME }}|g' k8s/deployment.yml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yml