name: CI/CD Pipeline 

on: [push]

jobs:
  train_and_test:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      # Checkout code 
      - name: Checkout code
        uses: actions/checkout@v3

      # Cài đặt các thư viện 
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install -g @dvcorg/cml 

      # Train model và log kết quả
      - name: Train Model and Log Results
        run: |
          python src/train.py
          echo "# Training Report" > report.md
          cat metrics.txt >> report.md
          echo "![](./residuals.png)" >> report.md

      # Test model 
      - name: Run tests
        run: |
          python src/test.py
          echo "## Single test Results" >> report.md
          cat single_test.txt >> report.md


      - name: Report
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cml comment create report.md

  build_and_deploy:
    needs: train_and_test 
    runs-on: ubuntu-latest

    steps:
      # Checkout code 
      - name: Checkout code
        uses: actions/checkout@v3

      # Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-demo:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-demo:latest

      # Replace Docker Hub username in deployment.yml 
      - name: Replace Docker Hub username in deployment.yml
        run: |
          sed -i 's|<DOCKER_HUB_USERNAME>|${{ secrets.DOCKER_HUB_USERNAME }}|g' k8s/deployment.yml

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yml