name: CI/CD Pipeline 

on: [push]

jobs:
  train_and_test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code từ GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Thiết lập Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Cài đặt các thư viện phụ thuộc
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install -g @dvcorg/cml  # Cài đặt CML

      # Train model và log kết quả
      - name: Train Model and Log Results
        run: |
          python src/train.py
          echo "# Training Report" > report.md
          cat metrics.txt >> report.md
          echo "![](./residuals.png)" >> report.md

      # Test mô hình sau khi train
      - name: Run tests
        run: |
          python src/test.py
          echo "## Single test Results" >> report.md
          cat single_test.txt >> report.md
          

      # Gửi báo cáo qua email với CML
      - name: Send Email with CML
        env:
          CML_GITHUB_TOKEN: ${{ secrets.CML_GITHUB_TOKEN }}
        run: |
          cml-send-comment report.md
