name: CI/CD Pipeline 

on: [push]

jobs:
  train_and_test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code từ GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Thiết lập Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Cài đặt các thư viện phụ thuộc
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install -g @dvcorg/cml  # Cài đặt CML

      # Train model và log kết quả
      - name: Train Model and Log Results
        run: |
          python src/train.py
          echo "# Training Report" > report.md
          cat metrics.txt >> report.md
          echo "![](./residuals.png)" >> report.md

      # Test mô hình sau khi train
      - name: Run tests
        run: |
          python src/test.py
          echo "## Single test Results" >> report.md
          cat single_test.txt >> report.md
          

      # Gửi báo cáo qua email
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: 'smtp.gmail.com' 
          server_port: 587                
          username: ${{ secrets.EMAIL_USERNAME }}  
          password: ${{ secrets.EMAIL_PASSWORD }} 
          from: ${{ secrets.GMAIL_USERNAME }}
          to: 'tranducthuan220401@gmail.com'  
          subject: 'MLOps Training Report'
          body: 'Training report.'
          attachments: 'report.md'
