name: CI/CD Pipeline 

on:
  push:
    paths-ignore:
      - README.md
jobs:
  test_before_train:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install -g @dvcorg/cml 

      - name: Run tests
        run: |
          python src/unittest_before_train.py
          echo "## Testing before train Results" > report.md
          cat test_results_before_train.txt >> report.md

      - name: Report
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cml comment create report.md

  train:
    needs: test_before_train
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install -g @dvcorg/cml 

      - name: Train Model and Log Results
        run: |
          python src/train.py
          echo "# Training Report" > report.md
          cat metrics.txt >> report.md
          echo "![](./confusion_matrix.png)" >> report.md
          echo "![](./classification_report.png)" >> report.md

      - name: Report
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cml comment create report.md

  test_after_train:
    needs: train
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install -g @dvcorg/cml 

      - name: Run tests
        run: |
          python src/unittest_after_train.py
          echo "## Testing after train Results" > report.md
          cat test_results_after_train.txt >> report.md

      - name: Report
        env:
          REPO_TOKEN: ${{ secrets.TOKEN }}
        run: |
          cml comment create report.md

  build:
    needs: test_after_train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-demo:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-demo:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.1' 
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          mkdir -p $HOME/.kube
              echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
              aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name  ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Replace Docker Hub username in deployment.yml
        run: |
          sed -i 's|<DOCKER_HUB_USERNAME>|${{ secrets.DOCKER_HUB_USERNAME }}|g' k8s/deployment.yml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yml

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/my-app